version: '3.0'

services:
  grafana:
    container_name: 'grafanaplugin-map-panel'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-latest}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./plugins:/var/lib/grafana/plugins
      - ./dist:/var/lib/grafana/plugins/grafanaplugin-map-panel
